### ISSUE TITLE
TypeError: sub() got an unexpected keyword argument 'endpos'

### ISSUE THREAD

**Issue by hongtw** [mrabarnett/mrab-regex#549]
The keyword argument endpos works correctly in the environment with regex==2024.9.11 and Python 3.10.15
However, in regex==2024.11.6, it raises the error:
`TypeError: sub() got an unexpected keyword argument 'endpos'.`

```
re.sub(r'a', 'b', 'abab', endpos=2048)
```

**Comment by mrabarnett** [comment]
I think you're confusing the `regex` module (this package) with the `re` module (in Python's standard library).

In the `re` module, the `sub` function doesn't support `pos` and `endpos`, so that needs to be:

 ```
re.compile(r'a').sub('b', 'abab', endpos=2048)
```

I found that annoying, which is why I added them in the `regex` module.
