### ISSUE TITLE
Regex doesn't build using CPython main (3.13.0a0)

### ISSUE THREAD

**Issue by smontanaro** [mrabarnett/mrab-regex#508]
Building regex using CPython's main branch (nascent 3.13.0a0) fails with this error:

```
      gcc -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I/Users/skip/src/smontanaro.net/3.13a0/include -I/Users/skip/src/python/cpython/Include -I/Users/skip/src/python/cpython -c regex_3/_regex.c -o build/temp.macosx-13.4-arm64-cpython-313/regex_3/_regex.o
      regex_3/_regex.c:19566:22: error: call to undeclared function '_PyBytes_Join'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  result = _PyBytes_Join(joiner, join_info->list);
                           ^
      regex_3/_regex.c:19566:20: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                  result = _PyBytes_Join(joiner, join_info->list);
                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      1 warning and 1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```

I tried an obvious "fix" by defining ```Py_BUILD_CORE``` and including ```internal/pycore_bytesobject.h``` in ```_regex.c```. That got it to build, but attempts to import regex failed with

```
ImportError: dlopen(/Users/skip/src/smontanaro.net/3.13a0/lib/python3.13/site-packages/regex/_regex.cpython-313-darwin.so, 0x0002): symbol not found in flat namespace '__PyBytes_Join'
```

The fix for this is probably straightforward as well, but is outsite my experience. 

FWIW, platform is Apple M1 Pro on MacBook Pro running MacOS 13.4.1.

**Comment by mrabarnett** [comment]
That's strange.

If you look in https://github.com/python/cpython/blob/main/Modules/_sre/sre.c at line 1257 you'll see that the re module uses that function.

Is it no longer available for extensions from Python 3.13? If yes, how are you supposed to join bytestrings, i.e. do `b''.join(list_of_bytestrings)`?

**Comment by smontanaro** [comment]
Looks like ```internal/pycore_bytesobject.h``` is included from ```internal/pycore_long.h```. Again, adding these lines:

```
#define Py_BUILD_CORE
#include "internal/pycore_long.h"
```

allows the module to build, but import fails with the "flat namespace" message.

**Comment by smontanaro** [comment]
The above include change is a recent addition (2023-07-04). Here's the commit message:

```
commit ec931fc3943df0b94f2e250d7723892f2b3414bd
Author: Victor Stinner <vstinner@python.org>
Date:   Tue Jul 4 10:27:23 2023 +0200

    gh-106320: Remove _PyBytesWriter C API (#106399)
    
    Remove the _PyBytesWriter C API: move it to the internal C API
    (pycore_bytesobject.h).
```

I don't see recent changes to the sre code which looks like it needed to adapt to the change.

**Comment by mrabarnett** [comment]
Ah, well, I found a simple-enough workaround and I've released regex 2023.8.8. As `_PyBytes_Join` was the only real problem the error message mentioned, I'll close this issue.
